code:
  local_dir: $CONFIG_DIR/../../
description: AMLT
environment:
  image: waybaba/rl:debug
  setup:
  - echo "setup start..."
  - export UPRJDIR=/mnt/default/
  - export UDATADIR=/mnt/storage/data
  - export UOUTDIR=/mnt/storage/output
  - mkdir -p /mnt/storage/output /mnt/storage/data
  - echo "setup finished!"
  username: waybaba
search:
  job_template:
    command:
    - 'python entry/entry.py -m experiment=train_diffuser hydra/launcher=wsl_parallel
      wandb.buf_dir=true wandb.mode=online n_jobs=5 seed=1 tags=[test3]  '
    name: RL_Delayed_{experiment_name:s}_{auto:5s}
    sku: G1-P40
  max_trials: 10000
  params: []
  type: grid
storage:
  input:
    container_name: v-wangwei1
    local_dir: /home/v-wangwei1/storage
    mount_dir: /mnt/storage
    storage_account_name: resrchvc4data
target:
  name: msrresrchvc
  service: singularity
